title: Pagina

fields:
  title:
    label: Titel
    type:  text

  richtext:
    label: Tekst
    type:  wysiwyg

  Description:
    label: Beschrijving
    type: Text
    placeholder: Een korte beschrijving van de pagina (optioneel)
    width: 1
    validate: 
      maxLength: 150
