title: Pagina

files:
  sortable: true
  fields:
    alt:
      label: Alt
      type:  text

fields:
  title:
    label: Titel
    type:  text

  richtext:
    label: Tekst
    type:  wysiwyg

  Description:
    label: Beschrijving
    type: Text
    placeholder: Een korte beschrijving van de pagina (optioneel)
    width: 1/2
    validate: 
      maxLength: 150

  showImage:
    label: afbeelding(en) weergeven?
    type: radio
    options:
      ja: ja
      nee: nee
    default: ja
    width: 1/2
