title: Project

options:
  template: false

files:
  sortable: true
  fields:
    alt:
      label: Alt
      type:  text
      default: een afbeelding

pages: false

fields:
  title:
    label: Titel
    type:  text

  year:
    label: Jaar
    type:  text
    width: 1/4

  client:
    label: Cliënt
    type: text
    width: 1/4

  contractor:
    label: Aannemer
    type: text
    width: 1/4

  engineer:
    label: Constructeur
    type: text
    width: 1/4

  consultant:
    label: Consultant(s)
    type: text
    width: 1/4

  location:
    label: Locatie
    type: text
    width: 1/4

  program:
    label: Programma
    type: text
    width: 1/4

  area:
    label: Oppervlak
    type: text
    width: 1/4

  status:
    label: Status
    type: radio
    options:
      opgeleverd: opgeleverd
      in aanbouw: in aanbouw
      planning: planning
      prijsvraag: prijsvraag
      on hold: on hold
      studie: studie
    default: false
    width: 1/2

  description:
    label: Beschrijving
    type: text
    placeholder: Een korte beschrijving van het project (optioneel)
    width: 1/2
    validate: 
      maxLength: 150

  other:
    label: Overig
    type: structure
    entry: >
      {{label}}: {{text}}
    fields:
      label:
        label: Label
        type: text
      text:
        label: Tekst
        type: text

  richtext:
    label: Tekst
    type:  wysiwyg
